plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gengroup.packager'
    compileSdk 34

    defaultConfig {
        applicationId "APPLICATION_ID_PLACEHOLDER"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
